### PR TITLE
[WIP] Add tests for all CLJS public API's

### LINKED ISSUE #20: `nil` is not a valid state for `dispatch!` not `dispatch-sync!`
Hello, long time no bug report :smile: 

I noticed a small problem/inconsistency. When I `dispatch!` an event that's supposed to clear the current state by setting it to `nil`, the state isn't cleared at all. In fact it isn't changed.

Some code to show the problem :

``` clojure
(defmutli widget-controller (fn [event _ _ ] event))

(defmethod widget-controller :clear [_ _ _]
  {:state nil})
```

The problem comes from [the Reconciler](https://github.com/roman01la/citrus/blob/a71d740536ed0e02774873712ff5d6a75be29ce4/src/citrus/reconciler.cljs#L75). The line `(let [state-effects (filter (comp :state second) effects) ;; other bindings])` will prevent state declared with `nil` as a target value to be taken into account. Indeed, in the REPL :

``` clojure
(filter :a [{:a 1} {:a 2} {:a nil}])
;; => ({:a 1} {:a 2})
```

The problem doesn't happen if I `dispatch-sync!` instead. I think `dispatch-sync!` has the right behavior. `nil` is a totally valid value for piece of state.

Here's a solution, directly taken from the code of the binding for `other-effects` (just below the code linked above). First bad code example, second is solution :

``` clojure
;; Bad, current code
(let [effects [[:ctrl1 {:state 1 :some :effect}]
               [:ctrl2 {:state nil}]
               [:ctrl3 {:some :effect}]]] 
  (filter (comp :state second) effects))
;; => ([:ctrl1 {:state 1, :some :effect}]) ;; :ctrl2 has been filtered out ! Furthermore, the effects are still here (it's ok they're filtered just after though)

;; Good, solution proposed
(let [effects [[:ctrl1 {:state 1 :some :effect}]
               [:ctrl2 {:state nil}]
               [:ctrl3 {:some :effect}]]]
  (->> effects
       (map (fn [[cname effect]]
              [cname (select-keys effect [:state])]))
       (filter (comp seq second))))
;; => ([:ctrl1 {:state 1}] [:ctrl2 {:state nil}]) ;; :ctrl2 still here and only :state effects \o/
```

Note : I'm still using `[org.roman01la/scrum "2.1.0-SNAPSHOT" :exclusions [rum]]` but I'm not asking you to fix this old version. I'll move to citrus soon.

In the meantime, I'll just put an empty map when `:clear`ing state.

End of bug report. Have a nice day !

### PR DESCRIPTION
**Pull request by DjebbZ**
[WIP]: Work in progress. No bug is fixed apparently with the change of reconciler.cljs.

The goal is to fix #20.

So I decided to setup a minial testing environment with Doo that runs a Firefox, to be abel to reproduce the bug and make sure it's fixed.

We'll see how it goes !

### CODE REVIEW

**Comment by DjebbZ** [comment]
I should rebase on master when I have time, you've just released 3.0.1

**Comment by DjebbZ** [comment]
I decied to test completely the public API and found how to test asynchronous dispatches with `requestAnimationFrame`. No override was necessary, no usage of private API/stuff. Just normal test code.

However several tests fail and I have no idea why. Testing asynchronous errors is really hard, since one needs to mess with global error handlers, and it doesn't seem to please the testing framework (Karma). Furthermore, some testing don't mess at all with error handlers and still don't pass...

Global error handlers : I tried several things, nothing worked :
- the clean way : `(.addEventListener js/window "error" err-handler)` (and the corresponding `.removeEventListener`)
- the dirty way : `(set! (.-onerror js/window) err-handler)` (and the corresponding `(set!)` to `nil`)
- the less-but-still dirty way : `(goog.object/set js/window "onerror" err-handler)`
- also tried keeping a reference to the existing error handler in case of, and setting it back (with `(goog.obj/get js/window "onerror"`)

No luck. And in all cases I took care of verifying if the others passing tests were really passing by changing the assertions, sometimes they didn't.

So several things are possible at this point :
- I may be lacking some knowledge
- Something is wrong with Karma or cljs.test
- Something is wrong with Citrus

My intuition say it's a combination of all 3 haha.

Seriously, could you have a look ? I think it could help preventing other bugs. I even tried to revert the fix for #23 but the tests operated the same... Need to fix them first.

Thanks for reading this (kinda) long report ! Need a break...

**Comment by DjebbZ** [comment]
By the way, it's rebased on top of master with `3.0.1`.

**Comment by DjebbZ** [comment]
Rebased on top of the latest changes (introduction of cofx). Need to read more about them in reframe's docs.

**Comment by roman01la** [comment]
Hmm, I have all 9 tests passing successfully.

**Comment by DjebbZ** [comment]
As it is now, yes, but what if you uncomment the `#_` tests ?

**Comment by DjebbZ** [comment]
Until you finish the work on co-effects, I think the tests cover all CLJS public API now. We just need to fix the failing one and I think you'll have a pretty good coverage !

🎁

**Comment by DjebbZ** [comment]
Bumping. Do you think you'll have some time working on this ? I still don't understand why some tests fail.

**Comment by roman01la** [comment]
@DjebbZ Sorry. Don't have much time now :(

**Comment by DjebbZ** [comment]
That's fine. At least you have it in one side of your mind.

**Pull request closed without merging**
