### PR TITLE
Add LOTS of tests to CLJS part

### PR DESCRIPTION
**Pull request by DjebbZ**
I finally got to finalize all the tests I had started long ago. Good news: all green!

When I started to write them (see #22), Citrus was in 3.0.0 and many of them were failing. This branch is rebased on top of `master` all tests passed directly, including the new ones. Makes me pretty confident about the stability of citrus :+1: 

I'd love if could review, merge (or tell me what's wrong) then do a release.

I realize the only feature I haven't tested in the CLJS side is the new cofx thing.

### CODE REVIEW

**Comment by roman01la** [comment]
Whoah! Thanks! LGTM

**Comment by DjebbZ** [comment]
You're welcome.

We have another PR coming that should greatly improve performance for `rum/react` heavy applications with big state. It should be issued by @jacomyal in the next days/weeks hopefully.

We also have other plans for citrus since I think we're the biggest users of the lib. Will open an issue (or more) when we're ready.

**Comment by roman01la** [comment]
Sounds great! I’ll be happy to merge those improvements.

I’ve been thinking about batching/scheduling mechanism, do you think it’s teally needed in Citrus? Rum is already doing this. Not sure how valuable this in Citrus 🤔

**Comment by DjebbZ** [comment]
Not sure either, what problem is it supposed to solve exactly? And how do
you want to implement it?

Le mer. 18 juil. 2018 à 20:51, Roman Liutikov <notifications@github.com> a
écrit :

**Comment by roman01la** [comment]
It's already there, been there from day one actually. See #27

**Comment by DjebbZ** [comment]
Have no real opinion about it, the default rAF is fine I think. You could
if you want try the PR of @chpill in master now since it has a good test
suite :)

I think citrus could have enhancements in other places. As I said before
we'll open issues for each of them.

Le mer. 18 juil. 2018 à 23:31, Roman Liutikov <notifications@github.com> a
écrit :

**Pull request merged**
